name: Google Play Alpha

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"  # Matches "v1.2.3" but not "v1.2.3.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Read GitHub Secrets & Decrypt Encrypted Files
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: |
        ./decrypt-secrets.sh
        echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV

    - name: Gradle Publish APK
      run: ./gradlew publishReleaseApk
